# Generated by Django 5.2.12 on 2026-05-27 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('localidad', models.CharField(max_length=60, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=60, verbose_name='Provincia')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('cpa', models.CharField(max_length=20, verbose_name='CPA')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('user_django', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.usuario')),
                ('fechaAlta', models.CharField(max_length=20, verbose_name='Fecha de Alta')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('esSocio', models.BooleanField(default=False, verbose_name='Es Socio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('gestion.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.usuario')),
                ('titulo_habilitante', models.CharField(max_length=100, verbose_name='Título Habilitante')),
                ('institucion_habilitante', models.CharField(max_length=100, verbose_name='Institución Habilitante')),
                ('certificado', models.FileField(upload_to='archivo/certificados', verbose_name='Certificado')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('baja', 'Baja'), ('en_validación', 'En espera de Validación')], default='en_validación', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Profesor/a',
                'verbose_name_plural': 'Profesores',
            },
            bases=('gestion.usuario',),
        ),
    ]
