# Generated by Django 5.2.13 on 2026-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['-id'], 'verbose_name': 'Profesor/a', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('baja', 'Baja'), ('en_validacion', 'En espera de Validación')], default='en_validación', max_length=50, verbose_name='Estado'),
        ),
    ]
