# Generated by Django 5.2.13 on 2026-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('socio', 'Socio del club'), ('empleado', 'Empleado'), ('temporal', 'Promoción temporal')], max_length=50, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('programado', 'Programado'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], default='activo', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
    ]
