# Generated by Django 5.2.13 on 2026-05-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('programado', 'Programado'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido'), ('baja', 'Baja')], default='activo', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.CharField(choices=[('socio', 'Socio del club'), ('empleado', 'Empleado'), ('temporal', 'Promoción temporal'), ('torneo', 'Torneo')], max_length=50, verbose_name='Tipo'),
        ),
    ]
