# Generated by Django 5.2.13 on 2026-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_descuento_estado_alter_descuento_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descuento',
        ),
    ]
