# Generated by Django 5.2.13 on 2026-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión'),
        ),
    ]
