# Generated by Django 5.2.13 on 2026-05-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0002_rename_cantidad_descuento_porcentaje'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descuentos.descuento'),
        ),
        migrations.DeleteModel(
            name='Descuento',
        ),
    ]
