# Generated by Django 5.2.13 on 2026-05-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_estado_alter_pago_reserva'),
        ('reservas', '0002_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='reservas.reserva'),
        ),
    ]
