# Generated by Django 5.2.13 on 2026-06-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_estado_alter_pago_reserva'),
        ('reservas', '0002_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pagos.pago'),
        ),
    ]
