# Generated by Django 5.2.13 on 2026-05-31 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0003_rename_porcentaje_descuento_cantidad'),
        ('pagos', '0005_alter_pago_reserva'),
        ('reservas', '0002_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='descuentos.descuento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
