# Generated by Django 5.2.13 on 2026-06-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pago_reserva_alter_recibo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago'),
        ),
    ]
