# Generated by Django 5.2.13 on 2026-06-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_pago_descuento_alter_pago_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='pagos.pago'),
        ),
    ]
