# Generated by Django 5.2.13 on 2026-06-02 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_recibo_pago'),
        ('reservas', '0003_alter_reserva_cliente_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.tipopago'),
        ),
    ]
