# Generated by Django 5.2.13 on 2026-06-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_pago_estado_pago_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
    ]
