# Generated by Django 5.2.13 on 2026-06-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0002_rename_cantidad_descuento_porcentaje'),
        ('pagos', '0008_remove_pago_estado_remove_pago_reserva'),
        ('reservas', '0003_alter_reserva_cliente_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='descuentos.descuento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.tipopago'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='pagos.pago'),
        ),
    ]
