# Generated by Django 5.2.13 on 2026-06-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_alter_recibo_pago_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRestobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_mesa', models.IntegerField(verbose_name='Número de Mesa')),
                ('detalle', models.TextField(verbose_name='Detalle del Consumo (Ej: 2 Cocas, 1 Hamburguesa)')),
                ('total_consumo', models.FloatField(verbose_name='Total Bruto ($)')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
