# Generated by Django 5.2.13 on 2026-06-03 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_pedidorestobar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorestobar',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.tipopago'),
        ),
    ]
