# Generated by Django 5.2.13 on 2026-06-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_pedidorestobar_tipo_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoRestobar',
        ),
    ]
