services:
 dbpsql:
   image: postgres:17
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   restart: always
   env_file:
      - .env.prod
 django-web:
   build: .
   container_name: golahora
   ports:
     - "8000:8000"
   depends_on:
     - dbpsql
   volumes:
     - ./static:/app/staticfiles
   restart: always
   env_file:
     - .env.prod
volumes:
   postgres_data: