# Generated by Django 5.2.12 on 2026-05-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Clase')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horario', models.DateTimeField(verbose_name='Horario')),
                ('cupo_maximo', models.PositiveIntegerField(default=10)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='clases', to='gestion.cliente')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='gestion.profesor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Entrenamiento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horario', models.DateTimeField(verbose_name='Horario')),
                ('cupo_maximo', models.PositiveIntegerField(default=10)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='entrenamientos', to='gestion.cliente')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos', to='gestion.profesor')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_clase', to='clases_y_entrenamientos.clase')),
            ],
            options={
                'verbose_name': 'Asistencia a clase',
                'verbose_name_plural': 'Asistencias a clases',
                'unique_together': {('clase', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_entrenamiento', to='clases_y_entrenamientos.entrenamiento')),
            ],
            options={
                'verbose_name': 'Asistencia a entrenamiento',
                'verbose_name_plural': 'Asistencias a entrenamientos',
                'unique_together': {('entrenamiento', 'alumno')},
            },
        ),
    ]
