# Generated by Django 5.2.12 on 2026-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_y_entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
    ]
