# Generated by Django 5.2.12 on 2026-06-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases_y_entrenamientos', '0002_clase_estado_entrenamiento_estado'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['horario'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='entrenamiento',
            options={'ordering': ['horario'], 'verbose_name': 'Entrenamiento', 'verbose_name_plural': 'Entrenamientos'},
        ),
        migrations.AlterField(
            model_name='asistenciaclase',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cliente'),
        ),
        migrations.AlterField(
            model_name='asistenciaentrenamiento',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cliente'),
        ),
    ]
