# Generated by Django 5.2.12 on 2026-06-02 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Inscripcion', 'En Inscripcion'), ('En_Curso', 'En Curso'), ('Finalizada', 'Finalizada')], default='Inscripcion', max_length=20)),
            ],
            options={
                'verbose_name': 'Competicion',
                'verbose_name_plural': 'Competiciones',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='integrantes',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='clientes',
            field=models.ManyToManyField(blank=True, to='competiciones.cliente', verbose_name='Integrantes (Clientes)'),
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('competicion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competiciones.competicion')),
                ('puntos_victoria', models.IntegerField(default=3)),
                ('puntos_empate', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
            bases=('competiciones.competicion',),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('competicion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='competiciones.competicion')),
                ('es_ida_y_vuelta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
            bases=('competiciones.competicion',),
        ),
        migrations.AddField(
            model_name='competicion',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='competiciones', to='competiciones.equipo'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('fase', models.CharField(max_length=50)),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('penales_local', models.IntegerField(blank=True, null=True)),
                ('penales_visitante', models.IntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competiciones.cancha')),
                ('competicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='competiciones.competicion')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='competiciones.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='competiciones.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competiciones.profesor', verbose_name='Profesor Asignado'),
        ),
    ]
