# Generated by Django 5.2.12 on 2026-06-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competiciones', '0002_cancha_cliente_competicion_profesor_and_more'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.profesor', verbose_name='Profesor Asignado'),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
