# Generated by Django 5.2.13 on 2026-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Cancha')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad (Jugadores)')),
                ('superficie', models.CharField(max_length=100, verbose_name='Superficie')),
            ],
            options={
                'verbose_name': 'Tipo de Cancha',
                'verbose_name_plural': 'Tipos de Canchas',
            },
        ),
    ]
