# Generated by Django 5.2.13 on 2026-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocancha',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo / Disponible'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tipocancha',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Hora'),
        ),
    ]
