# Generated by Django 5.2.13 on 2026-06-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocancha',
            name='limite_horas',
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo / Disponible'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='canchas.tipocancha')),
            ],
        ),
    ]
