# Generated by Django 5.2.13 on 2026-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_tipocancha_estado_tipocancha_precio_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocancha',
            name='superficie',
            field=models.CharField(choices=[('cesped_natural', 'Césped Natural'), ('sintetico', 'Césped Sintético')], default='sintetico', max_length=50, verbose_name='Superficie'),
        ),
    ]
