# Generated by Django 5.2.15 on 2026-06-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocancha',
            name='max_horas',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad máxima de horas seguidas que se puede alquilar este tipo de cancha.', verbose_name='Máximo de horas por reserva'),
        ),
    ]
