# Generated by Django 5.2.15 on 2026-06-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='canchas.tipocancha'),
        ),
    ]
