# Generated by Django 5.2.15 on 2026-06-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_tipocancha_max_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(help_text='Ej: Cancha N° 1 Techada', max_length=100, verbose_name='Nombre de la Cancha'),
        ),
    ]
