# Generated by Django 5.2.15 on 2026-06-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_alter_cancha_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocancha',
            old_name='nombre',
            new_name='nombreTipo',
        ),
    ]
