# Generated by Django 5.2.13 on 2026-06-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDescuento', models.CharField(max_length=50, verbose_name='Tipo de descuento')),
            ],
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='descuentos.tipodescuento'),
        ),
    ]
