# Generated by Django 5.2.13 on 2026-05-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='cantidad',
            new_name='porcentaje',
        ),
    ]
