# Generated by Django 5.2.13 on 2026-05-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0002_rename_cantidad_descuento_porcentaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='porcentaje',
            new_name='cantidad',
        ),
    ]
