# Generated by Django 5.2.13 on 2026-05-30 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_tipocancha_superficie'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.tipocancha', verbose_name='Tipo de Cancha'),
        ),
    ]
