# Generated by Django 5.2.13 on 2026-05-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        # Migration 0001_initial now correctly references canchas.tipocancha,
        # so this AlterField is no longer needed
    ]
