# Generated by Django 5.2.13 on 2026-06-02 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_tipocancha_superficie'),
        ('gestion', '0002_tipocancha_precio'),
        ('reservas', '0002_alter_reserva_tipo_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.usuario', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canchas.tipocancha', verbose_name='Tipo de Cancha'),
        ),
    ]
